version: "3"
services:
  webserver:
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: inception_nginx
    restart: unless-stopped
    ports:
      - "433:433"
    volumes:
      - worddata:/home/svalenti/data/wd
    networks:
      - frontend
  application:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: inception_word
    restart: unless-stopped
    volumes:
      - worddata:/home/svalenti/data/wd
    networks:
      - backend
  db:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: inception_mariadb
    restart: unless-stopped
    volumes:
      - dbdata:/home/svalenti/data/db
    networks:
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  dbdata:
    driver: local
  worddata:
    driver: local
